build: false
shallow_clone: false
platform: 'x86'
clone_folder: C:\projects\ospek
branches:
  only:
    - windows

install:
  - cinst -y OpenSSL.Light
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - sc config wuauserv start= auto
  - net start wuauserv
  - cinst -y php
  - cd c:\tools\php72
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo mbstring.http_input=pass >> php.ini
  - echo mbstring.http_output=pass >> php.ini
  - echo sendmail_path=nul >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_pdo_mysql.dll >> php.ini
  - echo extension=php_pdo_pgsql.dll >> php.ini
  - echo extension=php_pdo_sqlite.dll >> php.ini
  - echo extension=php_pgsql.dll >> php.ini
  - echo extension=php_gd2.dll >> php.ini
  - cd C:\projects\ospek
  - SET PATH=C:\tools\php72;%PATH%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-source --no-interaction

test_script:
  - cd C:\projects\ospek
  - vendor\bin\phpunit.bat --debug